services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - tienda

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "kafka", "9092" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s
    networks:
      - tienda

  mysql8-tienda:
    container_name: mysql8-tienda
    image: mysql:8.4.3
    ports:
      - "3307:3306"
    restart: always
    networks:
      - tienda
    environment:
      MYSQL_DATABASE: db_tienda
      MYSQL_ROOT_PASSWORD: 1234

  eureka-server-tienda:
    container_name: eureka-server-tienda
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - tienda

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server-tienda
      - productos
      - pedidos
    networks:
      - tienda

  productos:
    container_name: productos
    build:
      context: ./productos
      dockerfile: Dockerfile
    depends_on:
      - eureka-server-tienda
      - kafka
      - mysql8-tienda
    networks:
      - tienda

  pedidos:
    container_name: pedidos
    build:
      context: ./pedidos
      dockerfile: Dockerfile
    depends_on:
      - eureka-server-tienda
      - kafka
      - mysql8-tienda
    networks:
      - tienda

  pagos:
    container_name: pagos
    build:
      context: ./pagos
      dockerfile: Dockerfile
    depends_on:
      - eureka-server-tienda
      - kafka
    networks:
      - tienda

networks:
  tienda: